### ISSUE TITLE
Wrong message in DataMatrix

### ISSUE THREAD

**Issue by leszekru** [adrianschlatter/ppf.datamatrix#13]
Example code:
```
from ppf.datamatrix import DataMatrix
from cairosvg import svg2png
from IPython.display import Image, display

s = 'SD0000-REF-C0-I0'
myDataMatrix = DataMatrix(s).svg()
svg = svg2png(myDataMatrix,write_to=None,output_width=100,output_height=100)
display(Image(svg))
```

Result: 
![image](https://github.com/adrianschlatter/ppf.datamatrix/assets/4155346/05d9fd00-8062-4282-b233-2608e8f9d93b)

This image decodes to "SD0000-REF-C0-I0 U03" and some non-printable characters.

Expected result (from demo https://datalog.github.io/demo/datamatrix-svg/):
![datamatrix-20230518-072157](https://github.com/adrianschlatter/ppf.datamatrix/assets/4155346/410b9107-9ad1-42af-a5f2-9e702112e688)
Which decodes correctly, with any message.

I noticed that a "small" change in message results in the correct datamatrix -  'SD0000-R-C0-I0' works well.

**Comment by adrianschlatter** [comment]
Yes, I can reproduce this.

**Comment by adrianschlatter** [comment]
ppf.datamatrix uses edifact to encode this message, datamatrix-svg does not. The edifact encoded length in ppf.datamatrix is 13, in datamatrix-svg it is 14!

=> Apparently, there is a bug in our edifact encoder.

**Comment by adrianschlatter** [comment]
datamatrix-svg always adds a return to ascii code. ppf.datamatrix does not, if all characters fit into edifact groups (thereby saving space). Apparently, this causes problems in some - but apparently not all - cases.
