### ISSUE TITLE
Rectangular Datamatrix with garabage at the end are generated for short texts

### ISSUE THREAD

**Issue by ogelpre** [adrianschlatter/ppf.datamatrix#16]
Firstly, thank you for this excellent library. While attempting to implement a datamatrix code in [labelprinterkit](https://github.com/ogelpre/labelprinterkit) with this library, I encountered an issue.

This is a small example code:

```python
from ppf.datamatrix import DataMatrix
dm = DataMatrix('Hello World!', rect=True)
with open('/tmp/test.svg', 'w') as fh:
    fh.write(dm.svg())
```
I am using the current develop branch ([a9e292c](https://github.com/adrianschlatter/ppf.datamatrix/commit/a9e292c94f938e038b4ada55224eeb7a2c2297a6)) on Python 3.11.4.

The code above gives this result:
![defect datamatrix code](https://github.com/adrianschlatter/ppf.datamatrix/assets/831265/2c27457f-7616-4972-866b-4c2f1c6f7356)

My barcode reader is giving the following output: "Hello World!gmlqqy[)>06". As you can see, there is some garbage at the end of the line.

Generating the same string with the tools from https://www.bcgen.com/datamatrix-barcode-creator.html gives a bit different output:
![working datamatrix code](https://github.com/adrianschlatter/ppf.datamatrix/assets/831265/b54d8855-2c98-4815-b439-a4d2b24d21b0)

Which is read fine by my barcode reader.

I don't know if this is a bug or if something is broken in my setup. Maybe someone can try to confirm this issue?

**Comment by ogelpre** [comment]
I found the cause for this issue. It is in the codec selection process:

https://github.com/adrianschlatter/ppf.datamatrix/blob/a9e292c94f938e038b4ada55224eeb7a2c2297a6/src/ppf/datamatrix/datamatrix.py#L95-L101

The loop is not ended after the first codec. Multiple codecs are used for the same string. Inserting a break after line 98 fixes the issue.

**Comment by ogelpre** [comment]
It looks like the text codec has a bug. If I force the usage of C40 or ascii codec the garbage is gone.

**Comment by ogelpre** [comment]
datamatrix generated with https://datalog.github.io/demo/datamatrix-svg/ looks also different:
![datamatrix-svg](https://github.com/adrianschlatter/ppf.datamatrix/assets/831265/31fed765-91c5-49bf-9f05-c9ee55ef11c6)

**Comment by simonabler** [comment]
> It only happens with text codec. If I force the usage of C40 or ascii codec the garbage is gone.

How are you doing this?

**Comment by adrianschlatter** [comment]
Confirmed.
```
DataMatrix('Hello World!', rect=True, codecs=['text'])
```
fails.

But
```
DataMatrix('Hello World!', rect=True, codecs=['C40'])
```
is ok.

On the other hand with square matrices,
```
DataMatrix('Hello World!', rect=False, codecs=['text'])
```
is ok! => Apparently, it is not just a codec problem.

Then again
```
DataMatrix('Hello World!', rect=False, codecs=['C40'])
```
fails.

**Comment by adrianschlatter** [comment]
datamatrix-svg uses ASCII for 'Hello World!' whereas ppf.datamatrix uses TEXT. Apparently, TEXT encoding is shorter with ppf.datamatrix because ppf.datamatrix skips a 'return to ascii' code at the end (there is no next character, so why should it waste space for a 'return to ascii'-code?). This seems similar to issue #13.

**Comment by simonabler** [comment]
> ```
> DataMatrix('Hello World!', rect=False, codecs=['C40'])
> ```

codecs is not in the __init__ definition of the constructor? Version 0.1.2
DataMatrix.__init__() got an unexpected keyword argument 'codecs'
