### ISSUE TITLE
Add viewbox to allow to scale via CSS

### ISSUE THREAD

**Issue by micw** [adrianschlatter/ppf.datamatrix#18]
Hello,

the SVG cannot be scaled via CSS since the path is absolute. If you add viewBox="0 0 W H" (e.g. viewBox="0 0 18 18" if the width and height is 18), scaling works very well.

**Comment by adrianschlatter** [comment]
I think I agree with this. The current height and width attributes seem unnecessary, though.

**Comment by jpeg2600** [comment]
@adrianschlatter  It would be very nice if that fix was pushed to the pypi package 😇 thanks for your great work
