### ISSUE TITLE
Making the margin in the SVG output optional

### ISSUE THREAD

**Issue by hillstub** [adrianschlatter/ppf.datamatrix#21]
Right now, there seems to be a margin of 1px around the datamatrix when outputting to SVG. Would it be possible to make this optional? (happy to create a pull request)

**Comment by adrianschlatter** [comment]
Many things are possible. What would be the reasoning for having a no-margin option?

**Comment by denschub** [comment]
I don't want to create a new issue, so I'll just comment here, but

> What would be the reasoning for having a no-margin option?

I'm currently using `ppf.datamatrix` to generate datamatrix codes to print out on a label printer. The printer itself already has a fairly big print margin, so I want the generated code to be as big as possible.
