### ISSUE TITLE
how can i save the dm result？ 

### ISSUE THREAD

**Issue by jiachen0212** [adrianschlatter/ppf.datamatrix#3]
hello， i want save the dm_result, as jpg or png.. what can i do? @adrianschlatter

**Comment by jiachen0212** [comment]
> hello， i want save the dm_result, as jpg or png.. what can i do? @adrianschlatter
![屏幕快照 2022-01-05 下午2 30 04](https://user-images.githubusercontent.com/29834982/148170969-15d62144-b4e0-4919-9685-29d0af7d3e8b.png)

**Comment by adrianschlatter** [comment]
Simply call the .svg() method and you get the datamatrix as Scalable Vector-Graphics.
